{
    "workbench.iconTheme": "vscode-icons",
    "editor.formatOnSave": true,
    "[html]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "window.titleBarStyle": "custom",
    "vsicons.dontShowNewVersionMessage": true,
    "workbench.startupEditor": "none",
    "workbench.colorTheme": "Bearded Theme Vivid Black",
    "glassit.alpha": 240,
    "workbench.statusBar.visible": false,
    "editor.minimap.enabled": false,
    "workbench.sideBar.location": "right",

    "editor.copyWithSyntaxHighlighting": false,
    "diffEditor.ignoreTrimWhitespace": false,
    "editor.emptySelectionClipboard": false,
    "workbench.editor.enablePreview": false,
    "window.newWindowDimensions": "inherit",
    "editor.multiCursorModifier": "ctrlCmd",
    "files.trimTrailingWhitespace": true,
    "diffEditor.renderSideBySide": false,
    "editor.snippetSuggestions": "top",
    "editor.detectIndentation": false,
    "window.nativeFullScreen": true,
    "files.insertFinalNewline": true,
    "files.trimFinalNewlines": true,
  "workbench.editor.showTabs": "none",
  "editor.guides.indentation": false,
    "scm.diffDecorations": "none",
    "editor.hover.delay": 1500,
    "editor.hover.enabled": true,
    "editor.matchBrackets": "never",
    "workbench.tips.enabled": false,
    "editor.colorDecorators": false,
    "git.decorations.enabled": true,
    "editor.lightbulb.enabled": "off",
    "editor.selectionHighlight": false,
    "editor.overviewRulerBorder": false,
    "editor.renderLineHighlight": "none",
    "editor.occurrencesHighlight": "off",
    "problems.decorations.enabled": false,
    "editor.renderControlCharacters": false,
    "editor.hideCursorInOverviewRuler": true,
    "editor.gotoLocation.multipleReferences": "goto",
    "editor.gotoLocation.multipleDefinitions": "goto",
    "editor.gotoLocation.multipleDeclarations": "goto",
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "editor.gotoLocation.multipleImplementations": "goto",
    "editor.gotoLocation.multipleTypeDefinitions": "goto",

    // Custome Styles and Scripts
    "vscode_custom_css.imports": [
      "file:///C:/Users/linde/CraftDev/vscode/custom_vscode.css",
      "file:///C:/Users/linde/CraftDev/vscode/vscode-script.js"
  ],
  "editor.stickyScroll.enabled": false,
  "workbench.activityBar.location": "hidden",

  // Typography
  "editor.fontFamily": "'Hack Nerd Font Propo'",
  "security.workspace.trust.untrustedFiles": "open",
  "git.openRepositoryInParentFolders": "always",
  "editor.lineNumbers": "relative",
  "editor.cursorBlinking": "expand",
  "breadcrumbs.enabled": false,
  "editor.guides.bracketPairs": "active",
  "editor.bracketPairColorization.independentColorPoolPerBracketType": true,
  "window.menuBarVisibility": "compact"
  }
